language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7-dev"
install: pip install tox-travis
script: tox
after_script:
    - pip install scrutinizer-ocular
    - ocular --data-file ".coverage"
